In [ ]:
!pip install -U datasets
!pip install -U mlflow

In [ ]:
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer


MODEL_NAME = "arnir0/Tiny-LLM"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForCausalLM.from_pretrained(MODEL_NAME)

def generate_text(prompt, model, tokenizer, max_length=512, temperature=1, top_k=50, top_p=0.95):
    inputs = tokenizer.encode(prompt, return_tensors="pt")

    outputs = model.generate(
        inputs,
        max_length=max_length,
        temperature=temperature,
        top_k=top_k,
        top_p=top_p,
        do_sample=True
    )


    generated_text = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return generated_text

def main():
    # Define your prompt
    prompt = "According to all known laws of aviation, there is no way a bee should be able to fly."

    generated_text = generate_text(prompt, model, tokenizer)

    print(generated_text)

if __name__ == "__main__":
    main()

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.


According to all known laws of aviation, there is no way a bee should be able to fly.
This is a very easy-to-use system that provides a user-friendly interface to a remote system. However, by keeping their own rules in mind, it does not allow a voice to make it uncomplicated or unbiased or excite infringement, or are trying to find a suitable tool for anyone who wants to look at all of their friends for a long time.
It's very important to have great experiences in common areas of knowledge, such as for the purpose of training or teaching it or learning to have a career pathway
Another way to gain access to information that may be valuable to the people of any other way in which the "women are in the real world," which means they may have been better understand.
In your experience, they cannot say what you are doing with others.
In 2013, the people who do not know what it has to be.
Things on the Internet. It is a very common thing for bothers, the good old ones are not in the beginning

In [ ]:
import torch
from transformers import AutoModelForSequenceClassification, AutoTokenizer, TrainingArguments, Trainer
import pandas as pd
from sklearn.model_selection import train_test_split
from datasets import Dataset, load_dataset, concatenate_datasets
import numpy as np
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
import wandb

In [ ]:
# Login using e.g. `huggingface-cli login` to access this dataset
dataset = load_dataset("mteb/tweet_sentiment_extraction")

In [ ]:
dataset['test'], dataset['train']

(Dataset({
     features: ['text', 'label'],
     num_rows: 3534
 }),
 Dataset({
     features: ['text', 'label'],
     num_rows: 27481
 }))

In [ ]:
train_dataset = dataset['train']
eval_dataset = dataset['test']

In [ ]:
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token


def tokenize_function(examples):
    return tokenizer(examples["text"], padding="max_length", truncation=True)

tokenized_train_dataset = train_dataset.map(tokenize_function, batched=True)
tokenized_eval_dataset = eval_dataset.map(tokenize_function, batched=True)

Map:   0%|          | 0/3534 [00:00<?, ? examples/s]

In [ ]:
tokenized_train_dataset

Dataset({
    features: ['text', 'label', 'input_ids', 'attention_mask'],
    num_rows: 27481
})

In [ ]:
print(tokenized_train_dataset[0])

{'text': ' I`d have responded, if I were going', 'label': 1, 'input_ids': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2

In [ ]:
concatenated_dataset = concatenate_datasets([dataset['train'], dataset['test']])
concatenated_dataset.unique('label')
num_of_labels = len(concatenated_dataset.unique('label'))
num_of_labels

3

In [ ]:
model = AutoModelForSequenceClassification.from_pretrained(MODEL_NAME, num_labels=num_of_labels, pad_token_id=tokenizer.pad_token_id) # Adjust num_labels

Some weights of LlamaForSequenceClassification were not initialized from the model checkpoint at arnir0/Tiny-LLM and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [ ]:
def compute_metrics(pred):
    labels = pred.label_ids
    preds = pred.predictions.argmax(-1)
    precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average='weighted')
    acc = accuracy_score(labels, preds)
    return {
        'accuracy': acc,
        'f1': f1,
        'precision': precision,
        'recall': recall
    }

# Need to try out MLFlow instead of WandB

In [ ]:
import mlflow
mlflow.autolog()

2025/05/13 16:13:45 INFO mlflow.tracking.fluent: Autologging successfully enabled for keras.
2025/05/13 16:13:47 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
2025/05/13 16:13:47 INFO mlflow.tracking.fluent: Autologging successfully enabled for tensorflow.
2025/05/13 16:13:47 WARNING mlflow.utils.autologging_utils: MLflow transformers autologging is known to be compatible with 4.35.2 <= transformers <= 4.51.2, but the installed version is 4.51.3. If you encounter errors during autologging, try upgrading / downgrading transformers to a compatible version, or try upgrading MLflow.
2025/05/13 16:13:47 INFO mlflow.tracking.fluent: Autologging successfully enabled for transformers.
2025/05/13 16:13:47 WARNING mlflow.spark: With Pyspark >= 3.2, PYSPARK_PIN_THREAD environment variable must be set to false for Spark datasource autologging to work.
2025/05/13 16:13:47 INFO mlflow.tracking.fluent: Autologging successfully enabled for pyspark.


In [ ]:
with mlflow.start_run():
    # your training code goes here
    # Initialize W&B

    training_args = TrainingArguments(
        output_dir="./results",
        eval_strategy="epoch",
        learning_rate=4e-3,
        per_device_train_batch_size=32,
        per_device_eval_batch_size=32,
        num_train_epochs=1,
        weight_decay=0.01,
        report_to="mlflow",  # Enable mlflow integration
        run_name="my-awesome-run" # Custom run name
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_train_dataset,
        eval_dataset=tokenized_eval_dataset,
        compute_metrics=compute_metrics,
        processing_class=tokenizer
    )

    trainer.train()

    ...

<ipython-input-28-5f109b7a53bf>:17: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(


In [ ]:
mlflow.last_active_run()

<Run: data=<RunData: metrics={'epoch': 1.0,
 'eval_accuracy': 0.543010752688172,
 'eval_f1': 0.5123836675709043,
 'eval_loss': 0.9378683567047119,
 'eval_precision': 0.5728921374638508,
 'eval_recall': 0.543010752688172,
 'eval_runtime': 21.1139,
 'eval_samples_per_second': 167.378,
 'eval_steps_per_second': 5.257,
 'grad_norm': 4.675554275512695,
 'learning_rate': 0.0016763678696158325,
 'loss': 1.2322,
 'total_flos': 236910062075904.0,
 'train_loss': 1.1228706972701725,
 'train_runtime': 409.2264,
 'train_samples_per_second': 67.154,
 'train_steps_per_second': 2.099}, params={'_attn_implementation_autoset': 'True',
 '_name_or_path': 'arnir0/Tiny-LLM',
 'accelerator_config': "{'split_batches': False, 'dispatch_batches': None, "
                       "'even_batches': True, 'use_seedable_sampler': True, "
                       "'non_blocking': False, 'gradient_accumulation_kwargs': "
                       'None}',
 'adafactor': 'False',
 'adam_beta1': '0.9',
 'adam_beta2': '0.999',
 

In [ ]:
# In one cell, run this to start MLflow UI in the background:
get_ipython().system_raw("mlflow ui --port 5000 &")

In [ ]:
!pip install pyngrok -q
from pyngrok import ngrok

# Replace "YOUR_AUTHTOKEN" with your actual authtoken
ngrok.set_auth_token("2x37djQBYiKtStTpbABhLL8XwuM_3RaK7yMctKoBP36VRZzxa")

public_url = ngrok.connect(5000) # Default MLflow UI port
print(public_url)

NgrokTunnel: "https://8717-34-16-235-223.ngrok-free.app" -> "http://localhost:5000"


In [ ]:
# Kill existing processes
!kill $(ps aux | grep '[n]grok' | awk '{print $2}') > /dev/null 2>&1
!kill $(ps aux | grep '[m]lflow ui' | awk '{print $2}') > /dev/null 2>&1

# Start MLflow UI, explicitly binding to 0.0.0.0
get_ipython().system_raw("mlflow ui --host 0.0.0.0 --port 5000 &")

import time
time.sleep(5)

from pyngrok import ngrok
# ngrok.set_auth_token("YOUR_AUTHTOKEN") # Assumed done
public_url = ngrok.connect(addr="5000", proto="http")
print(public_url)

NgrokTunnel: "https://945d-34-16-235-223.ngrok-free.app" -> "http://localhost:5000"


In [ ]:
!cp -r ./mlruns "/content/drive/MyDrive/Colab Notebooks/LLM Fine-tuning Training/"

In [ ]:
# # Initialize W&B
# wandb.init(project="sentiment-analysis")

# training_args = TrainingArguments(
#     output_dir="./results",
#     eval_strategy="epoch",
#     learning_rate=4e-3,
#     per_device_train_batch_size=32,
#     per_device_eval_batch_size=32,
#     num_train_epochs=1,
#     weight_decay=0.01,
#     report_to="wandb",  # Enable WandB integration
#     run_name="my-awesome-run" # Custom run name
# )

# trainer = Trainer(
#     model=model,
#     args=training_args,
#     train_dataset=tokenized_train_dataset,
#     eval_dataset=tokenized_eval_dataset,
#     compute_metrics=compute_metrics,
#     tokenizer=tokenizer
# )

# trainer.train()

# wandb.finish()

In [ ]:
text = "rtherhte rhte rher hre herh erth "
inputs = tokenizer(text, return_tensors="pt").to("cuda")
outputs = model(**inputs)
predictions = torch.nn.functional.softmax(outputs.logits, dim=-1)
predicted_class = torch.argmax(predictions).item()
print(f"Predicted Class: {predicted_class}")

Predicted Class: 0


In [ ]:
from sklearn.metrics import confusion_matrix
import torch
import numpy as np

model.eval()
model.to("cuda")  # Ensure model is on GPU
all_preds = []
all_labels = []

for i in range(len(tokenized_eval_dataset)):
    batch = tokenized_eval_dataset[i]
    with torch.no_grad():
        input_ids = torch.tensor(batch['input_ids']).unsqueeze(0).to("cuda") # Add batch dimension
        attention_mask = torch.tensor(batch['attention_mask']).unsqueeze(0).to("cuda") # Add batch dimension
        labels = torch.tensor(batch['label']).unsqueeze(0).to("cuda") # Add batch dimension

        outputs = model(input_ids, attention_mask=attention_mask, labels=labels) #Pass labels
        logits = outputs.logits
        predictions = torch.argmax(logits, dim=-1).cpu().numpy()
        all_preds.extend(predictions)
        all_labels.extend(labels.cpu().numpy())

cm = confusion_matrix(all_labels, all_preds)
print("Confusion Matrix:\n", cm)

Confusion Matrix:
 [[ 180  746   75]
 [ 125 1136  169]
 [  22  478  603]]
